name: BankNotes
version: ${project.version}
main: com.dariasc.banknotes.BankNotes
depend: [Vault]
commands:
  withdraw:
    usage: /withdraw <amount>
    description: Withdraw funds
  deposit:
    usage: /deposit
    description: Deposit Bank Note in hand
  banknotes:
    usage: /banknotes <reload/give>
    description: Admin Commands
